/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.Date;
import Classes.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import Connection.*;
import com.placeholder.PlaceHolder;
import java.util.logging.Level;
import java.util.logging.Logger;
import UI.Frames.Service_Assign;
/**
 *
 * @author Lenovo
 */
public class ReservationFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    Reservation reservation;
    DefaultTableModel tableModel = new DefaultTableModel();
    int roomnoo = 0;
    int guestnoo = 0;
    float roomPricee = 0f;
    int custidd = 0;
    String checkin;
    String checkout;
    Room r;
    date d;
    bill_1 b;
    java.sql.Date in;
    java.sql.Date out;

    public ReservationFrame() {
        initComponents();
        tableModel.addColumn("Room Number");
        tableModel.addColumn("Room Price");
        tableModel.addColumn("Room Type");
        tableModel.addColumn("Statue");
        tableModel.addColumn("Room Service");
        table.setModel(tableModel);
        try {
            String ConnectionSql = "jdbc:sqlserver://localhost:1433;Database=finaldb;integratedSecurity=true;";
            try (Connection conn = DriverManager.getConnection(ConnectionSql)) {
                java.sql.Statement st = conn.createStatement();
                String sql = "select * from room where isBusy=0";
                ResultSet res = st.executeQuery(sql);

                while (res.next()) {
                    tableModel.addRow(new String[]{
                        String.valueOf(res.getInt(1)),
                        String.valueOf(res.getFloat(2)),
                        res.getString(3),
                        String.valueOf(res.getBoolean(4)),
                        String.valueOf(res.getBoolean(5))});
                }

                st.close();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        showbill = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Room_No = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        rservice = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        guestno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        OtherService = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        custid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dayin = new javax.swing.JTextField();
        monthin = new javax.swing.JTextField();
        yearout = new javax.swing.JTextField();
        dayout = new javax.swing.JTextField();
        monthout = new javax.swing.JTextField();
        yearin1 = new javax.swing.JTextField();
        roomPrice2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(14, 2, 16));
        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Room Service:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 132, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Check In:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        showbill.setEditable(false);
        showbill.setColumns(20);
        showbill.setRows(5);
        jScrollPane4.setViewportView(showbill);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 419, 560, 150));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check Out:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BILL:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 419, -1, -1));

        Room_No.setForeground(new java.awt.Color(255, 255, 255));
        Room_No.setText("Room_No:");
        getContentPane().add(Room_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 14, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Duration Of Stay:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 255, -1, -1));
        getContentPane().add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 11, 106, -1));
        getContentPane().add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 252, 65, -1));

        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        rservice.setText("500 $");
        rservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rserviceActionPerformed(evt);
            }
        });
        getContentPane().add(rservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 128, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Guest_No:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 52, -1, -1));

        guestno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestnoActionPerformed(evt);
            }
        });
        getContentPane().add(guestno, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 49, 106, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,  new Boolean(false)},
                {null, null, null, null,  new Boolean(false)},
                {null, null, null, null,  new Boolean(false)},
                {null, null, null, null, null}
            },
            new String [] {
                "room_No", "room_price", "room_service", "room_type", "isBusy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 13, 551, 290));

        OtherService.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OtherService.setText("Other Service");
        OtherService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherServiceActionPerformed(evt);
            }
        });
        getContentPane().add(OtherService, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("room price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 93, -1, -1));

        custid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custidActionPerformed(evt);
            }
        });
        getContentPane().add(custid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 106, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        PlaceHolder holder1 = new PlaceHolder(dayin, "Day");
        dayin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayinActionPerformed(evt);
            }
        });
        getContentPane().add(dayin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 40, -1));

        PlaceHolder holderr = new PlaceHolder(monthin, "month");
        monthin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthinActionPerformed(evt);
            }
        });
        getContentPane().add(monthin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 40, -1));

        PlaceHolder holdddder = new PlaceHolder(yearout, "Year");
        yearout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearoutActionPerformed(evt);
            }
        });
        getContentPane().add(yearout, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 50, -1));

        PlaceHolder holderrr = new PlaceHolder(dayout, "Day");
        dayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayoutActionPerformed(evt);
            }
        });
        getContentPane().add(dayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 40, -1));

        PlaceHolder holdder = new PlaceHolder(monthout, "month");
        monthout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthoutActionPerformed(evt);
            }
        });
        getContentPane().add(monthout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 40, -1));

        PlaceHolder holder = new PlaceHolder(yearin1, "year");
        yearin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearin1ActionPerformed(evt);
            }
        });
        getContentPane().add(yearin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 50, -1));
        getContentPane().add(roomPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {

            Reservation reservation = new Reservation(roomnoo, guestnoo, in, out, custidd);
            try {
                bill_1 b = new bill_1();
                roomnoo = Integer.parseInt(roomno.getText().trim());
                custidd = Integer.parseInt(custid.getText().trim());
                guestnoo = Integer.parseInt(guestno.getText().trim());
                roomPricee = Float.parseFloat(roomPrice2.getText().trim());
                int d_in = Integer.parseInt(dayin.getText().trim());
                int m_in = Integer.parseInt(monthin.getText().trim());
                int y_in = Integer.parseInt(yearin1.getText().trim());
                try {
                    if (d_in > 0 && d_in <= 31 && m_in > 0 && m_in <= 12 && y_in >= 2021) {
                        checkin = (d_in + "-" + m_in + "-" + y_in);

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
                }
                int d_out = Integer.parseInt(dayout.getText().trim());
                int m_out = Integer.parseInt(monthout.getText().trim());
                int y_out = Integer.parseInt(yearout.getText().trim());
                try {
                    if (d_out > 0 && d_out <= 31 && m_out > 0 && m_out <= 12 && y_out >= 2021) {
                        checkout = (d_out + "-" + m_out + "-" + y_out);

                    }
                } catch (Exception h) {
                    JOptionPane.showMessageDialog(null, h.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
                }
                int y_inn = y_in - 1900;
                int y_outt = y_out - 1900;
                java.sql.Date in = new Date(y_inn, m_in, d_in);
                java.sql.Date out = new Date(y_outt, m_out, d_out);
                reservation.setRoom_No(roomnoo);
                reservation.setCustomer_ID(custidd);
                reservation.setRoom_price(roomPricee);
                reservation.setDate_in(in);
                reservation.setDate_out(out);
                try {
                    Reservation_connection.AddReservation(reservation);
                    JOptionPane.showMessageDialog(null, "Added Succsesfully", "Added", JOptionPane.INFORMATION_MESSAGE);

                } catch (SQLException ex) {
                    Logger.getLogger(ReservationFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex.toString());
                }
                  r.setRoom_No(roomnoo);
                  r.setRoom_price(roomPricee);
//            d.setCheckindate(checkin + "");
//            d.setCheckoutdate(checkout + "");

                String date1 = (checkin + ""); // checkin date
                String date2 = (checkout + ""); // checkout date
                String format = "dd/mm/yyyy";
                SimpleDateFormat sdf = new SimpleDateFormat(format);

                Date dateObj1 = (Date) sdf.parse(date1 + " ");
                Date dateObj2 = (Date) sdf.parse(date2 + "");

                // getTime() returns the number of milliseconds since January 1, 1970, 00:00:00 GMT represented by this Date object
                long diff = dateObj2.getTime() - dateObj1.getTime();

                double diffDays = (int) (diff / (24 * 60 * 60 * 1000));

                duration.setText(diffDays + "");
                d.setDurationofstay((int) diffDays);
                b.setDurationofstay((int) diffDays);
                if (rservice.isSelected()) {
                    showbill.setText(500+diffDays * (roomPricee * 14 / 100*guestnoo)+"");
                    b.setService(500);
                    b.setTotalbill((int) (diffDays * (roomPricee * 14 / 100) + 500));
                    showbill.setText("room price = " + roomPricee + "\n" + "duration of stay = " + diffDays + "\n" + "taxes = " + 14 + "%" + "\n" + "room service = " + b.getService() + "\n" + "other service" + "\n" + "totalbill = " + b.getTotalbill());
                 
                }
                b.setTotalbill(diffDays * (roomPricee * 14 / 100));
            showbill.setText("room price = " +roomPricee + "\n" + "duration of stay = " + diffDays + "\n" + "taxes = " + 14 + "%" + "\n" + "other service" + "\n" + "totalbill = " + b.getTotalbill());
            showbill.setText(diffDays * (roomPricee * 14 / 100*guestnoo)+"");
            } catch (NumberFormatException | ParseException xcp) {

                JOptionPane.showMessageDialog(null, xcp.getMessage(), "error", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_submitActionPerformed

    private void rserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rserviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rserviceActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        DefaultTableModel tableModel = new DefaultTableModel();

        int selectedRowIndex = table.getSelectedRow();

        roomno.setText(this.tableModel.getValueAt(selectedRowIndex, 0).toString());
        roomPrice2.setText(this.tableModel.getValueAt(selectedRowIndex, 1).toString());


    }//GEN-LAST:event_tableMouseClicked

    private void OtherServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherServiceActionPerformed
        this.setVisible(true);
        new Service_Assign().setVisible(true);

    }//GEN-LAST:event_OtherServiceActionPerformed

    private void guestnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestnoActionPerformed

    private void custidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custidActionPerformed

    private void dayinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayinActionPerformed

    private void monthinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthinActionPerformed

    private void yearoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearoutActionPerformed

    private void dayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayoutActionPerformed

    private void monthoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthoutActionPerformed

    private void yearin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearin1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OtherService;
    private javax.swing.JLabel Room_No;
    private javax.swing.JTextField custid;
    private javax.swing.JTextField dayin;
    private javax.swing.JTextField dayout;
    private javax.swing.JTextField duration;
    private javax.swing.JTextField guestno;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField monthin;
    private javax.swing.JTextField monthout;
    private javax.swing.JTextField roomPrice2;
    private javax.swing.JTextField roomno;
    private javax.swing.JCheckBox rservice;
    private javax.swing.JTextArea showbill;
    private javax.swing.JButton submit;
    private javax.swing.JTable table;
    private javax.swing.JTextField yearin1;
    private javax.swing.JTextField yearout;
    // End of variables declaration//GEN-END:variables
}
