/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Frames;

//import frames.Panels.AddCustomer;
import java.awt.GridBagLayout;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Classes.*;
import UI.Frames.Panels.*;
import java.awt.GridBagConstraints;

/**
 *
 * @author Administrator
 */
public class CustomerFrame extends javax.swing.JInternalFrame {

    GridBagLayout layout = new GridBagLayout();

    AddCustomer p1;
    UpdateCustomer p2;
    CustomerDelete p3;

    Customer customer;

    /**
     * Creates new form MainMenu
     */
    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        initComponents();
        p1 = new AddCustomer();
        p2 = new UpdateCustomer();
        p3 = new CustomerDelete();
        DynamicPanel.setLayout(layout);
        

        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;

        DynamicPanel.add(p1, c);
        DynamicPanel.add(p2, c);
        DynamicPanel.add(p3, c);

      
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonInsert3 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        jButtonUpdate4 = new javax.swing.JButton();
        jButtonDelete5 = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setAlignmentX(390.0F);
        setAlignmentY(159.0F);
        setPreferredSize(new java.awt.Dimension(1166, 813));

        jPanel1.setBackground(new java.awt.Color(14, 2, 16));
        jPanel1.setPreferredSize(new java.awt.Dimension(1166, 813));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonInsert3.setBackground(new java.awt.Color(203, 200, 206));
        jButtonInsert3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInsert3.setForeground(new java.awt.Color(14, 2, 16));
        jButtonInsert3.setText("Add");
        jButtonInsert3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsert3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsert3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 43));

        DynamicPanel.setBackground(new java.awt.Color(14, 2, 16));
        DynamicPanel.setAlignmentX(0.0F);
        DynamicPanel.setAlignmentY(0.0F);
        DynamicPanel.setPreferredSize(new java.awt.Dimension(860, 520));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 0, 870, 530));

        jButtonUpdate4.setBackground(new java.awt.Color(203, 200, 206));
        jButtonUpdate4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonUpdate4.setForeground(new java.awt.Color(14, 2, 16));
        jButtonUpdate4.setText("Update");
        jButtonUpdate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 43));

        jButtonDelete5.setBackground(new java.awt.Color(203, 200, 206));
        jButtonDelete5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDelete5.setForeground(new java.awt.Color(14, 2, 16));
        jButtonDelete5.setText("Delete");
        jButtonDelete5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 43));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate4ActionPerformed
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdate4ActionPerformed

    private void jButtonDelete5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete5ActionPerformed
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelete5ActionPerformed

    private void jButtonInsert3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsert3ActionPerformed
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonInsert3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton jButtonDelete5;
    private javax.swing.JButton jButtonInsert3;
    private javax.swing.JButton jButtonUpdate4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
