/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Frames.Panels;


import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Connection.*;
import Classes.*;
import com.placeholder.PlaceHolder;

/**
 *
 * @author Farah
 */
public class Emp_add extends javax.swing.JPanel {

    /**
     * Creates new form Emp_add
     */
    Employee employee;
    int employee_ID = 0;
    String employee_fN = "";
    String employee_lN = "";
    String employee_department = "";

    public Emp_add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(14, 2, 16));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlaceHolder holder = new PlaceHolder(jTextField1, "Please enter ID");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 390, 30));

        PlaceHolder holder1= new PlaceHolder(jTextField2, "Please enter First Name");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 390, 30));

        PlaceHolder holder2 = new PlaceHolder(jTextField3, "Please enter Last Name");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 390, 30));

        PlaceHolder holdeer = new PlaceHolder(jTextField4, "Please enter Department");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 390, 30));

        jLabel6.setFont(new java.awt.Font("Century", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Employee");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Department");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("First Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jButton1.setText("Insert");
        jButton1.setPreferredSize(new java.awt.Dimension(140, 52));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 140, 52));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    try {
            Employee employee = new Employee(employee_ID, employee_fN, employee_lN, employee_department);
            try {
                employee_ID = Integer.parseInt(jTextField1.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ID should be numbers", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            try {
                employee_fN = jTextField2.getText().trim();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Name should be letters", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            try {
                employee_lN = jTextField3.getText().trim();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Name should be letters", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            try {
                employee_department = jTextField4.getText().trim();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "department be letters", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            employee.setEmployee_ID(employee_ID);
            employee.setEmployee_fN(employee_fN);
            employee.setEmployee_lN(employee_lN);
            employee.setEmployee_department(employee_department);
            Employee_CRUD.insertEmployeedata(employee);

            JOptionPane.showMessageDialog(null, "Added Succsesfully", "ADD", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null,e.toString());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {
            Employee employee = new Employee(employee_ID, employee_fN, employee_lN, employee_department);
            try {
                employee_ID = Integer.parseInt(jTextField1.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ID should be numbers", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            try {
                employee_fN = jTextField2.getText().trim();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Name should be letters", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            try {
                employee_lN = jTextField3.getText().trim();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Name should be letters", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            try {
                employee_department = jTextField4.getText().trim();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "department be letters", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            employee.setEmployee_ID(employee_ID);
            employee.setEmployee_fN(employee_fN);
            employee.setEmployee_lN(employee_lN);
            employee.setEmployee_department(employee_department);
            Employee_CRUD.insertEmployeedata(employee);

            JOptionPane.showMessageDialog(null, "Added Succsesfully", "ADD", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }

    public void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet.");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
