/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Frames.Panels;

import Classes.Service1;
import Connection.Service_CRUD;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Update_service extends javax.swing.JPanel {

    /**
     * Creates new form Update_service
     */
    Service1 service;
    String service_N = "";
    float service_price = 0;
    int service_code = 0;
    String service_description = "";
    int bill_id = 0;
    int customer_ID = 0;
    DefaultTableModel tableModel = new DefaultTableModel();

    public Update_service() {
        initComponents();
        tableModel.addColumn("Name");
        tableModel.addColumn("price");
        tableModel.addColumn("code");
        tableModel.addColumn("description");
        Service_table.setModel(tableModel);
        try {

            String ConnectionSql = "jdbc:sqlserver://localhost:1433;Database=finaldb;integratedSecurity=true;";
            Connection conn = DriverManager.getConnection(ConnectionSql);
            java.sql.Statement st = conn.createStatement();

            String sql = "select * from service1";
            ResultSet res = st.executeQuery(sql);

            while (res.next()) {

                tableModel.addRow(new String[]{
                    res.getString(1),
                    String.valueOf(res.getInt(2)),
                    String.valueOf(res.getInt(3)),
                    res.getString(4),});
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cid_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Service_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(14, 2, 16));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cid_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cid_txtActionPerformed(evt);
            }
        });
        add(cid_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, 30));

        jLabel1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 140, 60));

        Service_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        Service_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Service_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Service_table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 80, 540, 310));

        jLabel3.setFont(new java.awt.Font("Century", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Update Service");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, 30));
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, 30));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 120, 30));

        jLabel2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Code");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, -1));

        jLabel4.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cid_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cid_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cid_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Service1 service = new Service1(service_N, service_price, service_code, service_description);
            try {
                service_N = jTextField9.getText().trim();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Service NAME shold be letters", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            try {
                service_price = Float.parseFloat(jTextField10.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "price should be numbers", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            try {
                service_code = Integer.parseInt(cid_txt.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Service Code should be numbers", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            try {
                service_description = jTextField12.getText().trim();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Service Description should be letters", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            service.setService_N(service_N);
            service.setService_price(service_price);
            service.setService_code(service_code);
            service.setService_description(service_description);
            Service_CRUD.updateServiceData(service);
            JOptionPane.showMessageDialog(null, "Added Succsesfully", "ADD", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            Logger.getLogger(Update_service.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void Service_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Service_tableMouseClicked
        DefaultTableModel tableModel = new DefaultTableModel();
        int selectedRowIndex = Service_table.getSelectedRow();
        cid_txt.setText(this.tableModel.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_Service_tableMouseClicked

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Service_table;
    private javax.swing.JTextField cid_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
